[package]
name = "spade-docker"
description = "Manage Linux images for Spade"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
argh = "0.1.13"
dirs = "5.0.1"
serde = "1.0.217"
serde_json = "1.0.134"
