name: Docker Combine Images

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  CARGO_INCREMENTAL: 0

jobs:
  combine_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Combine images
        run: |
          docker manifest create ghcr.io/ethanuppal/spade-docker:latest \
            ghcr.io/ethanuppal/spade-docker:latest-x86_64 \
            ghcr.io/ethanuppal/spade-docker:latest-arm64
          docker manifest annotate ghcr.io/ethanuppal/spade-docker:latest ghcr.io/ethanuppal/spade-docker:latest-x86_64 --os linux --arch amd64
          docker manifest annotate ghcr.io/ethanuppal/spade-docker:latest ghcr.io/ethanuppal/spade-docker:latest-arm64 --os linux --arch arm64
          docker manifest push ghcr.io/ethanuppal/spade-docker:latest

          #docker buildx imagetools create --tag ghcr.io/ethanuppal/spade-docker:latest \
        #-f ghcr.io/ethanuppal/spade-docker:latest-x86_64 \
        # -f ghcr.io/ethanuppal/spade-docker:latest-arm64
