name: Docker

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2.7.3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - run: |
          cargo build
          chmod u+x ./spade-docker

      - name: Build and push image
        run: |
          ./spade-docker build --arch x86_64 --tag ghcr.io/ethanuppal/spade-docker:latest
          docker push ghcr.io/ethanuppal/spade-docker:latest
          ./spade-docker build --arch arm64 --tag ghcr.io/ethanuppal/spade-docker:latest
          docker push ghcr.io/ethanuppal/spade-docker:latest

